"""empty message

Revision ID: 415cc5347a24
Revises: 6a9324a46a00
Create Date: 2023-10-18 16:13:32.546863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415cc5347a24'
down_revision = '6a9324a46a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debt_generated', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('debt_generated')

    # ### end Alembic commands ###
