"""empty message

Revision ID: 9091e2ba723d
Revises: e36efdae1d7c
Create Date: 2023-10-07 12:05:49.907525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9091e2ba723d'
down_revision = 'e36efdae1d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomie', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
