"""empty message

Revision ID: c070e04d797a
Revises: 1b336ddc48c7
Create Date: 2023-10-05 19:46:59.381512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c070e04d797a'
down_revision = '1b336ddc48c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('checked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
