"""empty message

Revision ID: fc8342af1d42
Revises: c070e04d797a
Create Date: 2023-10-05 20:06:57.292570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8342af1d42'
down_revision = 'c070e04d797a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('expense_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('expense_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
